# Generated by Django 4.1.3 on 2022-12-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0002_pro_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='pro',
            old_name='details',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='pro',
            name='image',
        ),
        migrations.AddField(
            model_name='pro',
            name='co_non',
            field=models.CharField(default=11, max_length=10),
            preserve_default=False,
        ),
    ]
