# Generated by Django 4.1.3 on 2022-12-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0003_rank_rename_details_pro_type_remove_pro_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
